# File for module specific CMake tests.
include(DuneBoost)
find_package(BoostFusion 1.59 REQUIRED)
find_package(SuiteSparse COMPONENTS UMFPACK)
find_package(Eigen3)
if(${EIGEN3_FOUND})
  include_directories(${EIGEN3_INCLUDE_DIR})
  # dune_register_package_flags(INCLUDE_DIRS "${EIGEN3_INCLUDE_DIR}")
endif()
set(HAVE_EIGEN3 ${EIGEN3_FOUND})
include(AddSuiteSparseFlags)
